array:
- homo elmt
- mutable

lists:
- hetro elmt
- mutable

In [1]:
import numpy as np
# np is allias

## Numpy
maths and stats fn  
array manipulation & operations  

### Array creation
- np.array()
- np.random.rand(size)  
- np.random.randint(0,10, size= 5)  
- np.zeros()
- np.ones()
- np.empty()
- np.arange(start, stop, step, dtype=None)
- np.full(size, value)


### Datatypes
- integer --> int8, int16, int32, and int64 (bit-size)
- float --> float16, float32, and float64
- complex --> complex64 and complex128
- boolean --> np.bool_
- str --> dtype= str
- object --> dtype= object

type conversion --> var.astype(datatype) 

### Indexing & Slicing

Attributes:
- size - returns number of elements in the array
- dtype - returns data type of elements in the array
- itemsize - returns the size (in bytes) of each elements in the array
- reshape - changes the shape of the array to the desired dimensions
- ndim - dimension of arr


Indexing:
- arrray[index]
- array[row,col]
- array[]

Slicing:
- array[start:stop:step]
- mask --> filter to create sub array

### Operations
element wise operations (0,1 + 0,1)

- arthmetic : + - * / % (elmt wise oprt)
- np.sort()
- np.argsort() --> idices of sorted
- np.concatenate()
- np.reshape()
- np.sum()
- np.prod()
- np.cumsum() --> sum of the current and all previous elements.
- np.cumprod()
- np.add()
- np.substract()
- np.multiply()
- np.divide()
- < > >= <= == != (elmt wise)
- np.logical_and, 
- np.logical_or
- np.logical_not
- np.logical_xor

### Statistical fn
- np.mean() --> avg
- np.median()
- np.var() --> The average of the squared differences from the mean
- np.std() --> The square root of the variance, representing the dispersion of the data
- np.min() --> smallest value in arr
- np.max() --> largest value in array
- np.percentile() --> a score in the k-th percentile would be above approximately k% of all scores in its set

### String fn
- np.char.add()
- np.char.multiply()
- np.char.capitalize()
- np.char.title()
- np.char.lower()
- np.char.upper()
- np.char.split() --> split into lst
- np.char.splitlines()
- np.char.join(separator, arr)
- np.char.find(arr, substring)
- np.char.rfind() ->  returns the highest index in each string where the substring is found. If the substring is not found, it returns -1
- np.char.strip() --> remove white spaces
- np.char.isdigit()
- np.char.isalpha()
- np.char.isnumeric()
- np.column_stack() --> join col
- np.tile(np.concatenate([pair1, pair2]), n)

### Broadcasting
- Rule 1: If the arrays do not have the same rank, prepend the shape of the smaller array with ones until both shapes have the same length.
- Rule 2: The size in each dimension of the output shape is the maximum size in that dimension of the input shapes.
- Rule 3: An array can be broadcast across another array only if the size of the dimension in the array is 1 or matches the size of the dimension in the other array.


### Matrix
- np.transpose() --> row to col ()
- arr.T --> transpose
- np.linalg.inv()
- np.dot()

### Set operations
- np.unique() ---> returns the sorted unique elements of an array.
- np.intersect1d --> returns the sorted, unique values that are in both of the input arrays
- np.union1d --> returns the sorted, unique values that are in either of the input arrays
- np.setdiff1d --> returns the sorted, unique values in array1 that are not in array2


In [2]:
arr= np.array([1,2,3,4])

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
arr.ndim 
# dimensions

# dimension is diffn from size,shape

1

In [4]:
arr.shape
# number of elmt (row,col)


(4,)

In [5]:
arr2= np.array((23,45,77))
# tupple into array
print(arr2)

# list
lst= [1,3,4,5]
print(lst)

# diff betn arr (homo) and list (hetro)

[23 45 77]
[1, 3, 4, 5]


In [10]:
arr_2d= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [11,23,44]])

print(arr_2d)
print(type(arr_2d))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 23 44]]
<class 'numpy.ndarray'>


In [11]:
arr_2d.ndim

2

In [12]:
arr_2d.shape

# (rows,col)

(4, 3)

In [13]:
arr_3d= np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],

                  [[33,45,66],
                   [23,23,55],
                   [44,77,88]]])

print(arr_3d)
print(type(arr_3d))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[33 45 66]
  [23 23 55]
  [44 77 88]]]
<class 'numpy.ndarray'>


In [14]:
arr_3d.ndim

3

In [15]:
arr_3d.shape

# (2,3,3)
# 2 are sun arr (3,3) --> (rows, cols)

(2, 3, 3)

In [ ]:
arr_3d2= np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],

                  [[33,45,66],      #3*3
                   [23,23,55],
                   [44,77,88]],

                  [[3,44],      #3*2
                   [37, 33],
                   [23,44]]
                  ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

In [16]:
arr_3d3= np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],

                  [[33,45,66],
                   [23,23,55],
                   [44,77,88]],

                   [[36,44,55],
                    [23,4,44,],
                    [23,55,67]],

                   [[36,44,55],
                    [23,4,44,],
                    [23,55,67]]

                   ])

print(arr_3d3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[33 45 66]
  [23 23 55]
  [44 77 88]]

 [[36 44 55]
  [23  4 44]
  [23 55 67]]

 [[36 44 55]
  [23  4 44]
  [23 55 67]]]


In [17]:
arr_3d3.ndim

3

In [18]:
arr_3d3.shape

# (num of sub mx, row, col)

(4, 3, 3)

In [19]:
arr_3d3.itemsize

8

In [20]:
arr_3d3.dtype

# diff types of elmt, but not smtly

dtype('int64')

In [21]:
clrs= np.array(["red", "white", "purple"])
print(clrs)
print(type(clrs))

print(type(clrs[2]))

['red' 'white' 'purple']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [22]:
mix_arr= np.array(["apple", "banana", 23, 54])
print(mix_arr)
print(type(mix_arr))
print(mix_arr.dtype)

# here 23 and 54 converted generic (str)
# array --> homo

print(type(np.matrix[0]))
print(type(np.matrix[3]))

['apple' 'banana' '23' '54']
<class 'numpy.ndarray'>
<U21
<class 'types.GenericAlias'>
<class 'types.GenericAlias'>


In [23]:
num= np.array([1,2,3, 5.9])

print(num)

print(num.dtype)

[1.  2.  3.  5.9]
float64


In [24]:
num.itemsize

# size in bits of each elmt

8

In [27]:
x= np.array([1,2,4])

x.itemsize

# size of individual elmt

8

In [28]:
fruits= np.array(["apple", "mango", "orange", "ee"])

fruits.itemsize

24

In [29]:
print("data buffer", fruits.data)

# specific memory  location

data buffer <memory at 0x000002E17DD78280>


In [30]:
# indexing

print(arr)
print(arr2)

print(arr[2])
print(arr2[0])

[1 2 3 4]
[23 45 77]
3
23


In [31]:
print(arr_2d)

print(arr_2d[1][2])
print(arr_2d[1,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 23 44]]
6
6


In [39]:
print(arr_3d)

print(arr_3d[0,1,2])
print(arr_3d[1,0,0])
print(arr_3d[1,2,0])

print(arr_3d[0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[33 45 66]
  [23 23 55]
  [44 77 88]]]
6
33
44
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print(arr_3d[1,2,1])

77


In [41]:
# slicing

print(arr)
print(arr[2:])
print(arr[1:3])

[1 2 3 4]
[3 4]
[2 3]


In [42]:
print(arr2)

print(arr2[-1:])

[23 45 77]
[77]


In [43]:
print(arr_2d)

print(arr_2d[0:2, 1:])
print(arr_2d[0:2, 0:2])
print(arr_2d[1:2, 1:2])
print(arr_2d[-1,0:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 23 44]]
[[2 3]
 [5 6]]
[[1 2]
 [4 5]]
[[5]]
[11 23 44]


In [44]:
print(arr_3d)

print(arr_3d[1,1:2, 0:2])
print(arr_3d[0:2, 0:1, 1:3])
print(arr_3d[0:2, 1:, 0:2])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[33 45 66]
  [23 23 55]
  [44 77 88]]]
[[23 23]]
[[[ 2  3]]

 [[45 66]]]
[[[ 4  5]
  [ 7  8]]

 [[23 23]
  [44 77]]]
